### ISSUE TITLE
第一篇 吐槽搭建Github博客的艰苦历程 | Verlif浪费的时间

### ISSUE THREAD

**Issue by Verlif** [Verlif/verlif.github.io#2]
https://verlif.top/post/first/ 

 没有介绍，别想让我告诉你什么

**Comment by Verlif** [comment]
第一个留言

**Comment by kidoniko-blog** [comment]
第二个 加个友链呗 https://kidoniko.coding.me/

**Comment by alterfang** [comment]
群里有包！下载速度时好时坏

**Comment by Verlif** [comment]
> @kidoniko-blog
> 第二个 加个友链呗 https://kidoniko.coding.me/

我不会加T_T，可以教下吗

**Comment by Verlif** [comment]
> @alterfang
> 群里有包！下载速度时好时坏

好的，我都没注意到还有群
